// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'menu-refresh-metadata'
  | 'pref-enable'
  | 'pref-help'
  | 'pref-input'
  | 'pref-title'
  | 'refresh-failure'
  | 'refresh-failure-detail'
  | 'refresh-lookup-failed'
  | 'refresh-no-doi'
  | 'refresh-no-selection'
  | 'refresh-no-translator'
  | 'refresh-partial'
  | 'refresh-progress'
  | 'refresh-start'
  | 'refresh-success'
  | 'refresh-unknown-error'
  | 'untitled-item';
